#!/usr/bin/env python

import sys

def parse(fp):
    for line in fp:    
        if line[0:3] == ';;;':
            continue
        try:
            (word, syls) = line.split(' ',1)
        except:
            continue
        word = word.rstrip()
        if any(not (i >= 'A' and i <= 'Z' or i == '\'') for i in word):
            continue
        sys.stdout.write("%s %s\n"%(word, [i.isdigit() for i in syls].count(True)))


if __name__ == "__main__":
     parse(sys.stdin)
